townhall/myapi/dao.py, townhall/myapi/types.py
Created create_volunteer dao and CreateVolunteerData type
=> Created create_volunteer dao

townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/types.py
Created service method to add volunteer
=> Tow 18 create volunteer service

README.md, townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/tests.py
Write and set up a way to run tests on the project.  Added instructions on README how to run tests as well.
=> [TOW-53] Add test runners

townhall/myapi/migrations/0001_initial.py, townhall/myapi/models.py
Added an email field to the volunteer model class.
=> Tow 4 Create Volunteer Model

townhall/myapi/dao.py
Changed the dao create volunteer method to use the first_name and last_name fields instead of just name
=> Tow 4 dao create volunteer

townhall/myapi/tests.py
Changed the tests of the get volunteer info service method to include the email field
=> Changed the service method get volunteer info’s tests

townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/tests.py
- Added get_opportunity to dao.py and services.py
- Added test code for getting opportunities
=> get_opportunity

townhall/myapi/dao.py
Changed the method to pass instead of return none if the object is not found and also does not have a return value type
=> Slightly Changed the dao delete volunteer method

townhall/myapi/dao.py
Created and implemented the dao delete opportunity method, if a opporunity is found, it is deleted, if not, the method returns none
=> Created and implemented the dao delete opportunity method

townhall/myapi/services.py, townhall/myapi/tests.py
The update_volunteer test does the following :
- Checks if the volunteer exists
- Update the existing volunteer information
- Fetch the newly updated information, making sure the update was successful.
For additional test, we can delete step 2 and just fetch the already existing volunteer, which should pass as well since we're not updating anything.
=> added update volunteer services and tests

townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/tests.py
Created and implemented the service method for delete opportunity
Implemented tests that test for this functionality as well
=> Created and implemented the service delete opportunity method

townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/tests.py, townhall/myapi/types.py
Added filtering opportunity changes in types, dao, service method, and tests.
May need a deeper look and second opinion on the test for filtering out opportunities by name and time.
=> Filtering opportunities

townhall/myapi/dao.py, townhall/myapi/types.py
Also and create the update opportunity data types class in the types file
=> Implemented the dao update opportunity method 

townhall/myapi/dao.py, townhall/myapi/types.py
Method filters by name and location
=> Implemented the filter organizations dao method.

townhall/myapi/dao.py, townhall/myapi/serializers.py, townhall/myapi/services.py, townhall/myapi/views.py, townhall/townhall/urls.py
Similar to getting an opportunity by a single ID, this will fetch ALL opportunities. I added additional opportunities in Django Admin so we can fetch more than one opportunity for testing purposes.
- Run python manage.py runserver and in Postman, GET:  http://127.0.0.1:8000/opportunities/
=> Tow 44 Created GET endpoint to get ALL opportunities

townhall/myapi/dao.py, townhall/myapi/services.py
Also organized the import statements by model type for improved readability
=> Added missing import statements in the dao and services files

townhall/myapi/services.py, townhall/tests/test_organization.py
Tow 82
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-82
Tow 84
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-84
NO
This PR implements the service methods and tests for filter and delete organization.
-  I have ran all the tests locally, and they all pass
* This PR affects the organization service class and the organization tests file
- In doing these two tickets indirectIy learned about how to create a PR that is branched off of another PR.
=> Tow 82 84 service delete filter organization

townhall/myapi/services.py, townhall/tests/test_organization.py
Tow 35
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-35
Tow 36
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-36
Tow 83
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-83
NO
This PR is creating the service methods for the organization model. The create, update and get methods and their related tests.
- I have ran all the tests locally, and they all pass
* The Organization …
=> Tow 35 36 83 service create update get organization

townhall/myapi/admin.py
https://atriadev.atlassian.net/browse/TOW-68?atlOrigin=eyJpIjoiMTJlNWQ4OGEwMzkzNGQ1NjkxY2ZmZWZmYTFhMzE2NWQiLCJwIjoiaiJ9
NO
This allows the user to create a post and add multiple comments into that post.
Run server and in the Django admin, I created a post. Under that post, I was able to post multiple comments and view it.
Tow-68 (Adding image to a post)
List the areas in the app this PR is going to affect 
* admin.py
Learned how to create a table in django admin (TabularInline) for a neat and organized table for comments. Additionally learned how to add "multiple comments" into one singular post.
=> 1:M relationship between Post and Comment

townhall/myapi/views.py, townhall/townhall/settings.py, townhall/townhall/urls.py
https://atriadev.atlassian.net/browse/TOW-92?atlOrigin=eyJpIjoiZTAyYTMyMmFmMzIxNDBlOWFlMWNmNmYxNTFhOTM4ODEiLCJwIjoiaiJ9
NO :negative_squared_cross_mark:
Added methods to get all volunteers. Also added CORS to settings to connect the backend to the frontend.
-  [x] I have ran all the tests locally, and they all pass
List the areas in the app this PR is going to affect 
views.py
urls.py - added end point to get all volunteers to test the frontend
settings.py - added cors 
Setting up a connection between the frontend and backend when both are in separate repos.
=> Tow 92 get all volunteers

townhall/myapi/models.py
=> Tow 100 - Message model

townhall/myapi/views.py, townhall/tests/endpoint_tests/test_volunteer_endpoint.py, townhall/townhall/urls.py
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-178
- NO
- This PR is implementing and testing endpoint methods to get a volunteer, get all volunteers, and get all opportunities of a volunteer.
-  I have ran all the tests locally, and they all pass
- Doing this PR I have reinforced all of my learning about endpoints such as serializers, HTTP, etc
=> Tow 178 volunteer get endpoints

townhall/myapi/models.py, townhall/myapi/views.py, townhall/tests/endpoint_tests/test_volunteer_endpoint.py, townhall/townhall/urls.py
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ
- NO
- This PR implements the delete endpoints for the volunteer model.
- I have ran all the tests locally, and they all pass
- Doing this PR I reinforced all of my learned regarding creating and testing endpoints
=> Tow 181 delete endpoints volunteer

townhall/myapi/serializers.py, townhall/myapi/services.py, townhall/myapi/views.py, townhall/requirements.txt, townhall/tests/endpoint_tests/test_volunteer_endpoint.py, townhall/townhall/settings.py, townhall/townhall/urls.py
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-174
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-187
- NO :negative_squared_cross_mark:
- This PR adds the nesessary changes to utilize the Django Debugging Toolbar. This PR also optimizes queries to the database. Note there was not any major optimizations that could be made.
-  I have ran all the tests locally, and they all pass
- Doing this PR I further reinforced my learning about API endpoints and testing. I also a lot more about the specifics regarding the …
=> Tow 174 187 optimize daos and install debug toolbar

townhall/myapi/dao.py, townhall/myapi/serializers.py, townhall/myapi/services.py, townhall/myapi/types.py, townhall/myapi/views.py, townhall/requirements.txt, townhall/tests/endpoint_tests/test_volunteer_endpoint.py, townhall/tests/service_tests/test_volunteer_service.py, townhall/townhall/settings.py, townhall/townhall/urls.py
- https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-183
- NO :negative_squared_cross_mark:
- This PR implements 2 new Volunteer endpoints, to update a volunteer and to change a volunteers password. This PR also makes a few minor changes/additions.
-  I have ran all the tests locally, and they all pass
- This PR will mainly affect the volunteer endpoints area of the application.
- This PR served as a bit of review and reinforced my understanding of making API Endpoints, while working on this PR I also learned how to make custom Serializers that can make checks beyond just that of a pre existing model
=> Tow 183 volunteer patch endpoints

townhall/myapi/dao.py, townhall/myapi/serializers.py, townhall/myapi/services.py, townhall/myapi/types.py, townhall/myapi/views.py, townhall/tests/endpoint_tests/test_post_endpoint.py, townhall/tests/service_tests/test_post_service.py, townhall/townhall/urls.py
https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?assignee=601355d1f564b600711e24e4&selectedIssue=TOW-190
NO :negative_squared_cross_mark:
Added a POST endpoint for creating a new post object
-  [x] I have ran all the tests locally, and they all pass
General backend
I learned how to create and test an enpoint
=> Created POST endpoint to create a new post object

townhall/myapi/dao.py, townhall/myapi/services.py, townhall/myapi/types.py, townhall/myapi/views.py, townhall/townhall/urls.py
https://atriadev.atlassian.net/jira/software/projects/NT/boards/38?selectedIssue=NT-3
https://atriadev.atlassian.net/jira/software/projects/NT/boards/38?selectedIssue=NT-4
NO :negative_squared_cross_mark:
=> update and delete post

townhall/myapi/views.py
YES :white_check_mark: |  NO :negative_squared_cross_mark:
-  [ ] I have ran all the tests locally, and they all pass
List the areas in the app this PR is going to affect 
* Some Area
Describe in 1-2 sentences what you learned from doing this task
=> bug fix conten to content
